import { ProjectDocument } from '../domain/models/types';
import { addDays, getTodayString } from '../domain/utils/date';

export function createDefaultSampleProject(): ProjectDocument {
  const now = new Date().toISOString();
  return {
    schemaVersion: 1,
    exportedAt: now,
    project: {
      id: 'sample_phd_paper',
      name: 'Submit PhD Paper',
      endGoalNodeId: 'node_submit_paper',
      tags: ['Research', 'Academia'],
      style: { color: 'indigo', icon: 'graduation-cap' },
      createdAt: now,
      updatedAt: now,
    },
    nodes: [
      {
        id: 'node_submit_paper',
        projectId: 'sample_phd_paper',
        parentNodeId: null,
        text: 'Submit PhD Paper to Journal',
        dueDate: addDays(getTodayString(), 60),
        status: 'planned',
        position: { x: 900, y: 200 },
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'node_write_paper',
        projectId: 'sample_phd_paper',
        parentNodeId: null,
        text: 'Write PhD Paper Manuscript',
        dueDate: addDays(getTodayString(), 50),
        status: 'planned',
        position: { x: 620, y: 200 },
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'node_run_exp',
        projectId: 'sample_phd_paper',
        parentNodeId: null,
        text: 'Run Phantom Experiments',
        dueDate: addDays(getTodayString(), 20),
        status: 'completed',
        position: { x: 60, y: 200 },
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'node_prep_phantom',
        projectId: 'sample_phd_paper',
        parentNodeId: 'node_run_exp',
        text: 'Prepare Phantom Samples',
        dueDate: addDays(getTodayString(), 10),
        status: 'completed',
        position: { x: -200, y: 150 },
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'node_analyze',
        projectId: 'sample_phd_paper',
        parentNodeId: null,
        text: 'Analyze Reconstruction Noise',
        dueDate: addDays(getTodayString(), 35),
        status: 'in_progress',
        position: { x: 340, y: 120 },
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'node_validate',
        projectId: 'sample_phd_paper',
        parentNodeId: null,
        text: 'Validate Against Benchmark',
        dueDate: addDays(getTodayString(), 40),
        status: 'planned',
        position: { x: 340, y: 280 },
        createdAt: now,
        updatedAt: now,
      },
    ],
    edges: [
      {
        id: 'e1',
        projectId: 'sample_phd_paper',
        fromNodeId: 'node_prep_phantom',
        toNodeId: 'node_run_exp',
        createdAt: now,
      },
      {
        id: 'e2',
        projectId: 'sample_phd_paper',
        fromNodeId: 'node_run_exp',
        toNodeId: 'node_analyze',
        createdAt: now,
      },
      {
        id: 'e3',
        projectId: 'sample_phd_paper',
        fromNodeId: 'node_run_exp',
        toNodeId: 'node_validate',
        createdAt: now,
      },
      {
        id: 'e4',
        projectId: 'sample_phd_paper',
        fromNodeId: 'node_analyze',
        toNodeId: 'node_write_paper',
        createdAt: now,
      },
      {
        id: 'e5',
        projectId: 'sample_phd_paper',
        fromNodeId: 'node_validate',
        toNodeId: 'node_write_paper',
        createdAt: now,
      },
      {
        id: 'e6',
        projectId: 'sample_phd_paper',
        fromNodeId: 'node_write_paper',
        toNodeId: 'node_submit_paper',
        createdAt: now,
      },
    ],
    notes: [
      {
        id: 'note_exp',
        nodeId: 'node_run_exp',
        text: 'Had to repeat acquisition because the first scan had corrupted gradients.',
        createdAt: now,
        updatedAt: now,
      },
    ],
    history: [],
  };
}
